version: '3.9'

services:
  laravelapp:
    container_name: laravelapp
    image: francescoxx/laravelapp:1.0.1
    build: .
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - db
    
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}