version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  laravelapp:
    container_name: laravelapp
    image: francescoxx/laravelapp:1.0.1
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata: {}
